# Generated by Django 3.0.7 on 2020-06-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0003_auto_20200629_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolfamous',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolrank',
            name='school',
        ),
        migrations.DeleteModel(
            name='SchoolDetail',
        ),
        migrations.DeleteModel(
            name='SchoolFamous',
        ),
        migrations.DeleteModel(
            name='SchoolRank',
        ),
    ]
