# Generated by Django 2.2.13 on 2020-07-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0013_schoollist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollist',
            name='condition',
            field=models.CharField(default='', max_length=200),
        ),
    ]
