# Generated by Django 2.2.13 on 2020-07-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0018_schoollist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaokaoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2019', max_length=200)),
                ('wenli', models.CharField(default='1', max_length=200)),
                ('score', models.IntegerField(default=300)),
                ('rank', models.IntegerField(default=200)),
                ('rank_cum', models.IntegerField(default=200)),
            ],
        ),
    ]
