# Generated by Django 2.2.13 on 2020-07-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0019_gaokaometa'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaokaometa',
            name='province',
            field=models.CharField(default='河北', max_length=200),
        ),
    ]
