# Generated by Django 2.2.13 on 2020-07-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0020_gaokaometa_province'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GaokaoMeta',
            new_name='GaokaoMetaRank',
        ),
    ]
