# Generated by Django 2.2.13 on 2020-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0021_auto_20200710_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaokaoRecallRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('rank_win', models.TextField(blank=True, null=True)),
                ('rank_lose', models.TextField(blank=True, null=True)),
                ('rank_predict', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaokaoRecallScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('school_win', models.TextField(blank=True, null=True)),
                ('school_lose', models.TextField(blank=True, null=True)),
                ('school_predict', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
