# Generated by Django 2.2.13 on 2020-07-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0023_auto_20200712_0838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaokaoRecallRank',
        ),
        migrations.DeleteModel(
            name='GaokaoRecallScore',
        ),
    ]
