# Generated by Django 2.2.13 on 2020-07-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0027_gaokaorecallrank_gaokaorecallscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaokaoRecallRank',
        ),
        migrations.DeleteModel(
            name='GaokaoRecallScore',
        ),
    ]
