# Generated by Django 2.2.13 on 2020-07-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0030_delete_gaokaorecallrank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaokaoRecallScore',
        ),
    ]
