# Generated by Django 2.2.13 on 2020-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0034_gaokaorecallrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaokaoMetaScoreLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='河北', max_length=200)),
                ('wenli', models.CharField(default='1', max_length=200)),
                ('batch_name', models.CharField(default='本科第一批', max_length=200)),
                ('academic_year', models.CharField(default='2019', max_length=200)),
                ('school_line', models.IntegerField(default=0)),
            ],
        ),
    ]
