# Generated by Django 2.2.13 on 2020-07-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0042_auto_20200716_0730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
