# Generated by Django 2.2.13 on 2020-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0043_auto_20200716_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=200, null=True)),
                ('mname', models.CharField(blank=True, max_length=200, null=True)),
                ('cid', models.CharField(blank=True, max_length=200, null=True)),
                ('cname', models.CharField(blank=True, max_length=200, null=True)),
                ('sid', models.CharField(blank=True, max_length=200, null=True)),
                ('sname', models.CharField(blank=True, max_length=200, null=True)),
                ('academic_rule', models.CharField(blank=True, max_length=200, null=True)),
                ('careers', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('diploma_id', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
                ('major_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('major_type', models.CharField(blank=True, max_length=200, null=True)),
                ('employment_info', models.TextField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('knowledge_requirement', models.TextField(blank=True, null=True)),
                ('main_course', models.TextField(blank=True, null=True)),
                ('teaching_practice', models.TextField(blank=True, null=True)),
                ('training_objective', models.TextField(blank=True, null=True)),
                ('training_requirement', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
