# Generated by Django 2.2.13 on 2020-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0046_majorsplit_match_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MajorSplit',
        ),
    ]
