# Generated by Django 2.2.13 on 2020-07-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0052_schoolmajorsplit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolMajorSplit',
        ),
    ]
