# Generated by Django 2.2.13 on 2020-07-17 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0064_schoolmajorsplit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolMajorSplit',
        ),
    ]
