# Generated by Django 2.2.13 on 2020-07-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0080_modelruleresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRuleResult',
        ),
    ]
