# Generated by Django 2.2.13 on 2020-07-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0083_modelruleresult_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRuleResult',
        ),
    ]
