# Generated by Django 2.2.13 on 2020-07-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0086_delete_modelruleresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRuleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_major_id', models.CharField(blank=True, max_length=200, null=True)),
                ('enroll_major_name', models.CharField(blank=True, max_length=200, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('wenli', models.CharField(blank=True, max_length=200, null=True)),
                ('province_id', models.CharField(blank=True, max_length=200, null=True)),
                ('min_score_diff_mean', models.IntegerField(default=-1)),
                ('min_score_diff_std', models.IntegerField(default=-1)),
                ('min_score_rank_mean', models.IntegerField(default=-1)),
                ('min_score_rank_std', models.IntegerField(default=-1)),
                ('avg_score_diff_mean', models.IntegerField(default=-1)),
                ('avg_score_diff_std', models.IntegerField(default=-1)),
                ('avg_score_rank_mean', models.IntegerField(default=-1)),
                ('avg_score_rank_std', models.IntegerField(default=-1)),
                ('type', models.IntegerField(default=1)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaokao.School')),
            ],
        ),
    ]
