# Generated by Django 3.0.7 on 2020-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0002_schooldetail_schoolfamous_schoolrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetail',
            name='sch_abroad_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooldetail',
            name='sch_master_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='canteen_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='sch_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='sch_fellowship',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='sch_intro',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schooldetail',
            name='sch_scholarship',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
