# Generated by Django 2.2.13 on 2020-07-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0007_schoolmajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolList',
            fields=[
                ('condition', models.CharField(default='-1', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaokao.School')),
            ],
        ),
    ]
