# Generated by Django 2.2.13 on 2020-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0008_schoollist'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollist',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schoollist',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
