# Generated by Django 2.2.13 on 2020-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0010_auto_20200704_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
