# Generated by Django 2.2.13 on 2020-07-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0011_auto_20200704_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolList',
        ),
    ]
