# Generated by Django 2.2.13 on 2020-07-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0014_auto_20200705_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolList',
        ),
    ]
