# Generated by Django 2.2.13 on 2020-07-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0016_schoollist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolList',
        ),
    ]
