# Generated by Django 2.2.13 on 2020-07-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0022_gaokaorecallrank_gaokaorecallscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaokaorecallrank',
            name='batch_name',
            field=models.CharField(default='本科第一批', max_length=200),
        ),
        migrations.AddField(
            model_name='gaokaorecallrank',
            name='province',
            field=models.CharField(default='河北', max_length=200),
        ),
        migrations.AddField(
            model_name='gaokaorecallrank',
            name='wenli',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='gaokaorecallscore',
            name='batch_name',
            field=models.CharField(default='本科第一批', max_length=200),
        ),
        migrations.AddField(
            model_name='gaokaorecallscore',
            name='province',
            field=models.CharField(default='河北', max_length=200),
        ),
        migrations.AddField(
            model_name='gaokaorecallscore',
            name='wenli',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
