# Generated by Django 2.2.13 on 2020-07-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0032_gaokaorecallrank_gaokaorecallscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaokaoRecallRank',
        ),
    ]
