# Generated by Django 2.2.13 on 2020-07-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0039_schoolmajor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolMajor',
        ),
    ]
