# Generated by Django 2.2.13 on 2020-07-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0040_delete_schoolmajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_id', models.CharField(default='', max_length=200)),
                ('wenli', models.CharField(default='', max_length=200)),
                ('academic_year', models.CharField(default='', max_length=200)),
                ('batch', models.CharField(default='', max_length=200)),
                ('batch_name', models.CharField(default='', max_length=200)),
                ('diploma_id', models.CharField(default='', max_length=200)),
                ('academic_rule', models.CharField(blank=True, max_length=200, null=True)),
                ('admission_count', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_score', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_score_diff', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_score_rank', models.CharField(blank=True, max_length=200, null=True)),
                ('enroll_major_code', models.CharField(blank=True, max_length=200, null=True)),
                ('enroll_major_id', models.CharField(blank=True, max_length=200, null=True)),
                ('enroll_major_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enroll_plan_count', models.CharField(blank=True, max_length=200, null=True)),
                ('max_score', models.CharField(blank=True, max_length=200, null=True)),
                ('max_score_diff', models.CharField(blank=True, max_length=200, null=True)),
                ('max_score_rank', models.CharField(blank=True, max_length=200, null=True)),
                ('min_score', models.CharField(blank=True, max_length=200, null=True)),
                ('min_score_diff', models.CharField(blank=True, max_length=200, null=True)),
                ('min_score_rank', models.CharField(blank=True, max_length=200, null=True)),
                ('tuition', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gaokao.School')),
            ],
        ),
    ]
