# Generated by Django 2.2.13 on 2020-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0041_schoolmajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='major',
            name='major_name',
        ),
        migrations.RemoveField(
            model_name='major',
            name='school',
        ),
        migrations.AddField(
            model_name='major',
            name='academic_rule',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='careers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='cid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='cname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='diploma_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='employment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='knowledge_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='main_course',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='major_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='major_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='mid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='mname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='sid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='sname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='teaching_practice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='training_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='training_requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
