# Generated by Django 2.2.13 on 2020-07-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0050_auto_20200716_1436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolMajorSplit',
        ),
    ]
