# Generated by Django 2.2.13 on 2020-07-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0056_schoolmajorsplit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolMajorSplit',
        ),
    ]
