# Generated by Django 2.2.13 on 2020-07-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaokao', '0070_modelruleresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRuleResult',
        ),
    ]
